name: Deploy Angular Project

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config --global user.email "owtf086@gmail.com"
          git config --global user.name "ilyavtln"

      - name: Build project
        run: ng deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  display-deployment-link:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Create summary file with deployment link
        run: |
          echo "Website deployed! Visit it at https://ilyavtln.github.io/test-gh-pages" > deployment-summary.txt

      - name: Upload summary file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-summary
          path: deployment-summary.txt
